version: "2"

run:
  timeout: 5m
  issues-exit-code: 1

formatters:
  enable:
    - goimports
    - gofumpt

  settings:
    goimports:
      local-prefixes:
        - github.com/yuluo-yx/agentscope-go
    gofumpt:
      extra-rules: true
      module-path: github.com/yuluo-yx/agentscope-go

  exclusions:
    generated: lax

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused

  settings:

    goheader:
      template: |-
        Copyright The AgentScope Go Authors

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

    gocritic:
      disabled-checks:
        - ifElseChain
    goconst:
      min-len: 5
      min-occurrences: 4
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    gosec:
      excludes:
        - G404
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

    staticcheck:
      checks:
        # The default config:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        # Changes to the default config:
        - -QF1001 # Exclude "Apply De Morgan's law"
        - -QF1008 # Exclude "Omit embedded fields from selector expression"
        - -SA1019 # Exclude to keep the old a2a compatibility, can remove for ADK v2

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gocyclo
          - errcheck
          - gosec
          - revive
      - path: 'internal/httprr/.*'
        linters:
          - goheader
          - errcheck
          - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
