// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos/internal/biz"
	"kratos/internal/conf"
	"kratos/internal/server"
	"kratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	chatUsecase := biz.NewChatUsecase()
	chatService := service.NewChatService(chatUsecase)
	grpcServer := server.NewGRPCServer(confServer, chatService, logger)
	httpServer := server.NewHTTPServer(confServer, chatService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {}, nil
}
