apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: ${SANDBOX_WARMPOOL_NAME}
  namespace: ${SANDBOX_NAMESPACE}
spec:
  replicas: 0
  sandboxTemplateRef:
    name: ${SANDBOX_TEMPLATE_NAME}
