name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'Makefile'
      - 'tools/github-setup-deps/**'
      - 'tools/agentsandbox/**'
      - 'tools/make/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'Makefile'
      - 'tools/github-setup-deps/**'
      - 'tools/agentsandbox/**'
      - 'tools/make/**'
      - '.github/workflows/**'

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    if: github.repository == 'yuluo-yx/agentscope-go'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./tools/github-setup-deps
      - run: make download
      - run: make ci
      - run: make e2e E2E_PROFILE=docker
      - run: tools/agentsandbox/install-kind.sh
      - run: make e2e E2E_PROFILE=agent-sandbox
