name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'Makefile'
      - 'tools/github-setup-deps/**'
      - 'tools/agentsandbox/**'
      - 'tools/make/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - 'Makefile'
      - 'tools/github-setup-deps/**'
      - 'tools/agentsandbox/**'
      - 'tools/make/**'
      - '.github/workflows/**'

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    if: github.repository == 'yuluo-yx/agentscope-go'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./tools/github-setup-deps
      - run: make download
      - run: make ci
      - run: make test-e2e-docker
      - name: Install kind and kubectl
        run: |
          curl -fsSLo kind https://kind.sigs.k8s.io/dl/v0.30.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind
          curl -fsSLo kubectl https://dl.k8s.io/release/v1.34.2/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          kind version
          kubectl version --client=true
      - run: make test-e2e-agent-sandbox
